### ISSUE TITLE
Add Support for Symfony Process 6.x

### ISSUE THREAD

**Issue by BusterNeece** [ramsey/composer-repl#1]
The upstream Psysh project has implemented support for version 6.x of Symfony Console, so it would be advantageous to have support for version 6.x of Symfony Process in this project.

In my experience thus far with the 6.x upgrade, this should only represent a change in explicitly providing function argument types and return types, though that may also result in a change in the minimum supported PHP version.

**Comment by ramsey** [comment]
Thanks! I have several repos that need this update. I plan to get to it this week. Let me know if you'd like to submit a pull request, though.

**Comment by ramsey** [comment]
This is fixed in version 1.3.0. Thanks!
